// Generated by gen.py: cockpit paint colours per car body sprite (main, second), measured offline
// with the same rules as vhr_paint_colours. The matching recoloured driver art ships in the APK as
// vhrpaint_<sprite>.png, so the Quest build never does per-pixel work in GML.
function vhr_paint_table() {
    if(variable_global_exists("vhr_paint_tab")) return global.vhr_paint_tab;
    var _t=ds_map_create();
    ds_map_set(_t,"spr_car_mk4r_body_red",[make_colour_rgb(223,73,41),make_colour_rgb(246,230,219)]);
    ds_map_set(_t,"spr_car_mk4r_body_blue",[make_colour_rgb(89,196,254),make_colour_rgb(204,159,106)]);
    ds_map_set(_t,"spr_car_mk4r_body_gray",[make_colour_rgb(190,186,184),make_colour_rgb(204,159,106)]);
    ds_map_set(_t,"spr_car_mk4r_body_yellow",[make_colour_rgb(255,217,32),make_colour_rgb(80,108,136)]);
    ds_map_set(_t,"spr_car_mk4r_body_lavender",[make_colour_rgb(208,218,248),make_colour_rgb(171,143,199)]);
    ds_map_set(_t,"spr_car_pepe_green",[make_colour_rgb(152,222,27),make_colour_rgb(254,166,59)]);
    ds_map_set(_t,"spr_car_pepe_blue",[make_colour_rgb(89,165,241),make_colour_rgb(147,196,245)]);
    ds_map_set(_t,"spr_car_pepe_orange",[make_colour_rgb(255,127,0),make_colour_rgb(255,171,89)]);
    ds_map_set(_t,"spr_car_pepe_purple",[make_colour_rgb(210,94,226),make_colour_rgb(100,171,171)]);
    ds_map_set(_t,"spr_car_pepe_red",[make_colour_rgb(221,51,14),make_colour_rgb(171,171,227)]);
    ds_map_set(_t,"spr_car_cilantro_body_white",[make_colour_rgb(231,231,254),make_colour_rgb(29,162,21)]);
    ds_map_set(_t,"spr_car_cilantro_body_yellow",[make_colour_rgb(255,218,38),make_colour_rgb(0,126,253)]);
    ds_map_set(_t,"spr_car_cilantro_body_pink",[make_colour_rgb(245,191,248),make_colour_rgb(248,213,250)]);
    ds_map_set(_t,"spr_car_cilantro_body_gray",[make_colour_rgb(125,215,240),make_colour_rgb(208,67,51)]);
    ds_map_set(_t,"spr_car_cilantro_body_green",[make_colour_rgb(156,224,29),make_colour_rgb(18,152,128)]);
    ds_map_set(_t,"spr_car_gulf340_body_white",[make_colour_rgb(228,228,254),make_colour_rgb(144,176,255)]);
    ds_map_set(_t,"spr_car_gulf340_body_pink",[make_colour_rgb(255,192,203),make_colour_rgb(129,1,129)]);
    ds_map_set(_t,"spr_car_gulf340_body_seafoam",[make_colour_rgb(20,203,191),make_colour_rgb(98,98,164)]);
    ds_map_set(_t,"spr_car_gulf340_body_blue",[make_colour_rgb(50,165,254),make_colour_rgb(255,218,31)]);
    ds_map_set(_t,"spr_car_gulf340_body_red",[make_colour_rgb(217,69,69),make_colour_rgb(169,225,225)]);
    ds_map_set(_t,"spr_seagull",[make_colour_rgb(255,255,255),make_colour_rgb(255,255,255)]);
    ds_map_set(_t,"spr_trafficConeBIG",[make_colour_rgb(255,127,0),make_colour_rgb(171,171,227)]);
    ds_map_set(_t,"spr_testcar",[make_colour_rgb(192,188,177),make_colour_rgb(147,130,105)]);
    ds_map_set(_t,"spr_the_freak",[make_colour_rgb(212,212,212),make_colour_rgb(188,0,0)]);
    ds_map_set(_t,"spr_car_renzo_A",[make_colour_rgb(85,189,249),make_colour_rgb(234,234,254)]);
    ds_map_set(_t,"spr_car_renzo_B",[make_colour_rgb(210,210,213),make_colour_rgb(161,161,217)]);
    ds_map_set(_t,"spr_car_renzo_C",[make_colour_rgb(161,74,223),make_colour_rgb(161,161,217)]);
    ds_map_set(_t,"spr_car_renzo_D",[make_colour_rgb(204,65,36),make_colour_rgb(161,161,217)]);
    ds_map_set(_t,"spr_car_renzo_E",[make_colour_rgb(86,168,114),make_colour_rgb(161,161,217)]);
    ds_map_set(_t,"spr_car_minji_A",[make_colour_rgb(214,162,255),make_colour_rgb(218,110,10)]);
    ds_map_set(_t,"spr_car_minji_B",[make_colour_rgb(182,110,43),make_colour_rgb(207,160,117)]);
    ds_map_set(_t,"spr_car_minji_C",[make_colour_rgb(10,200,147),make_colour_rgb(218,110,10)]);
    ds_map_set(_t,"spr_car_minji_D",[make_colour_rgb(88,139,181),make_colour_rgb(218,110,10)]);
    ds_map_set(_t,"spr_car_minji_E",[make_colour_rgb(253,97,97),make_colour_rgb(253,152,152)]);
    ds_map_set(_t,"spr_car_anais_A",[make_colour_rgb(255,215,24),make_colour_rgb(80,108,136)]);
    ds_map_set(_t,"spr_car_anais_B",[make_colour_rgb(211,62,34),make_colour_rgb(80,108,136)]);
    ds_map_set(_t,"spr_car_anais_C",[make_colour_rgb(173,45,173),make_colour_rgb(80,108,136)]);
    ds_map_set(_t,"spr_car_anais_D",[make_colour_rgb(36,134,188),make_colour_rgb(112,176,211)]);
    ds_map_set(_t,"spr_car_anais_E",[make_colour_rgb(12,182,85),make_colour_rgb(80,108,136)]);
    ds_map_set(_t,"spr_car_lucy_A",[make_colour_rgb(121,121,175),make_colour_rgb(213,63,37)]);
    ds_map_set(_t,"spr_car_lucy_B",[make_colour_rgb(213,67,38),make_colour_rgb(227,132,113)]);
    ds_map_set(_t,"spr_car_lucy_C",[make_colour_rgb(213,63,37),make_colour_rgb(227,130,113)]);
    ds_map_set(_t,"spr_car_lucy_D",[make_colour_rgb(186,186,186),make_colour_rgb(213,63,37)]);
    ds_map_set(_t,"spr_car_lucy_E",[make_colour_rgb(90,156,156),make_colour_rgb(213,63,37)]);
    ds_map_set(_t,"spr_car_tommi_A",[make_colour_rgb(48,163,48),make_colour_rgb(136,176,209)]);
    ds_map_set(_t,"spr_car_tommi_B",[make_colour_rgb(197,61,33),make_colour_rgb(136,176,209)]);
    ds_map_set(_t,"spr_car_tommi_C",[make_colour_rgb(201,101,8),make_colour_rgb(136,176,209)]);
    ds_map_set(_t,"spr_car_tommi_D",[make_colour_rgb(165,166,166),make_colour_rgb(136,176,209)]);
    ds_map_set(_t,"spr_car_tommi_E",[make_colour_rgb(148,147,9),make_colour_rgb(136,176,209)]);
    ds_map_set(_t,"spr_car_hawk_A",[make_colour_rgb(244,124,4),make_colour_rgb(2,253,253)]);
    ds_map_set(_t,"spr_car_hawk_B",[make_colour_rgb(164,161,28),make_colour_rgb(195,193,107)]);
    ds_map_set(_t,"spr_car_hawk_C",[make_colour_rgb(131,159,187),make_colour_rgb(196,192,105)]);
    ds_map_set(_t,"spr_car_hawk_D",[make_colour_rgb(197,159,112),make_colour_rgb(217,192,162)]);
    ds_map_set(_t,"spr_car_hawk_E",[make_colour_rgb(26,138,199),make_colour_rgb(196,192,105)]);
    ds_map_set(_t,"spr_car_ace_A",[make_colour_rgb(236,109,109),make_colour_rgb(102,102,172)]);
    ds_map_set(_t,"spr_car_ace_B",[make_colour_rgb(254,165,59),make_colour_rgb(102,102,172)]);
    ds_map_set(_t,"spr_car_ace_C",[make_colour_rgb(222,95,221),make_colour_rgb(102,102,172)]);
    ds_map_set(_t,"spr_car_ace_D",[make_colour_rgb(83,158,233),make_colour_rgb(143,191,240)]);
    ds_map_set(_t,"spr_car_ace_E",[make_colour_rgb(143,144,145),make_colour_rgb(102,102,172)]);
    ds_map_set(_t,"spr_car_kenzi_A",[make_colour_rgb(219,97,221),make_colour_rgb(28,111,208)]);
    ds_map_set(_t,"spr_car_kenzi_B",[make_colour_rgb(8,198,146),make_colour_rgb(28,111,208)]);
    ds_map_set(_t,"spr_car_kenzi_C",[make_colour_rgb(255,131,9),make_colour_rgb(28,111,208)]);
    ds_map_set(_t,"spr_car_kenzi_D",[make_colour_rgb(246,187,49),make_colour_rgb(28,111,208)]);
    ds_map_set(_t,"spr_car_kenzi_E",[make_colour_rgb(246,200,175),make_colour_rgb(28,111,208)]);
    global.vhr_paint_tab=_t;
    return _t;
}
function vhr_paint_prebaked(_name) {
    return ds_map_find_value(vhr_paint_table(),_name);
}
// Recoloured driver art for that car, loaded once and kept for the whole session.
function vhr_driver_prebaked(_name) {
    if(!variable_global_exists("vhr_driver_assets")) global.vhr_driver_assets=ds_map_create();
    var _s=ds_map_find_value(global.vhr_driver_assets,_name);
    if(is_undefined(_s) || !sprite_exists(_s)) {
        _s=sprite_add("vhrpaint_"+string_lower(_name)+".png",1,false,false,0,0);
        ds_map_set(global.vhr_driver_assets,_name,_s);
    }
    return _s;
}
// Driver art with the grey background already removed (no per-pixel pass at load).
function vhr_driver_clean_prebaked() {
    if(!variable_global_exists("vhr_driver_clean") || !sprite_exists(global.vhr_driver_clean))
        global.vhr_driver_clean=sprite_add("vhrpaint_vhr-driver-clean.png",1,false,false,0,0);
    return global.vhr_driver_clean;
}
